default: &default
  adapter: postgresql
  encoding: unicode
  username: laki
  password: laki
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: article_app_development

test:
  <<: *default
  database: article_app_test

production:
  primary:
    <<: *default
    database: article_app_production
  cache:
    <<: *default
    database: article_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: article_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: article_app_production_cable
    migrations_paths: db/cable_migrate
